### ISSUE TITLE
Switch to gopacket/gopacket

### ISSUE THREAD

**Issue by shaunco** [libp2p/go-netroute#41]
Please switch from https://github.com/google/gopacket to https://github.com/gopacket/gopacket

**Comment by willscott** [comment]
this library is able to be used as a standalone component, but is also commonly used as part of https://github.com/libp2p/go-libp2p/blob/master/go.mod#L12

as such, this is a decision i would want to do as part of a migration at the libp2p level, rather than introduce the change of the alternate dep only in this sub-library.

is there a reason the gopacket fork was not created as a fork of the upstream library on github? it doesn't show up in the network of the google library, which makes it harder to identify as a clear direct successor,

**Comment by mosajjal** [comment]
the `gopacket/gopacket` project is not a git-level fork of `google/gopacket` because Google has shown no intention of merging the changes back to the original repo. having it as a standalone repository helps developers fork `gopacket/gopacket` and contribute directly. 

hope that clears it up.

**Comment by willscott** [comment]
I see no issue about it in `google/gopacket` - where was that lack of interest shown by previous maintainers?

**Comment by shaunco** [comment]
@willscott - Would still like to request this change. `google/gopacket` got its first update since 2021 in March 2025, to add `ague` and `apsp`. `gopacket/gopacket` brought those in, but also made about 15 other fixes/improvements since March. It really makes no sense for go-netroute (or libp2p) to stick to `google/gopacket`.
